name: GitHub secret scanning alert generated Playbook
description: Detect when a GitHub scan discovers a secret stored in a repository.
severity: Low
steps:
- name: Investigation
  description: 'Secret scanning is a security feature that identifies and prevents the accidental inclusion of sensitive information like API keys, passwords, and tokens in repositories. When activated, it examines commits across all branches for known types of secrets and alerts repository administrators upon detection. Additionally, GitHub periodically scans the full Git history of public repositories with secret scanning enabled.


    If a scan detects a potential secret, an alert is generated to notify repository administrators.


    ## Triage and response


    1. Assess whether the detected secret is sensitive for your environment.

    2. If the secret''s publication poses a risk, initiate your incident response process and investigate.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
