name: GitHub branch protection disabled on branch Playbook
description: Detect when branch protection has been disabled on a GitHub branch.
severity: Low
steps:
- name: Investigation
  description: 'This rule monitors audit logs for instances when branch protection has been disabled. Organizations can safeguard important branches by establishing branch protection rules, which dictate whether collaborators can delete or force push to the branch and set requirements for any pushes, such as passing status checks or maintaining a linear commit history. Disabling this protection may weaken the organization''s security posture.


    ## Triage and response

    1. Determine if the change made by the actor is authorized.

    2. If the change was unauthorized or unexpected, initiate the organization''s incident response process and investigate.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
