name: GitHub a branch protection requirement was overridden by a repository administrator Playbook
description: Detect when GitHub branch protection has been overridden by a repository administrator.
severity: Low
steps:
- name: Investigation
  description: 'This rule monitors GitHub audit logs for instances when branch protection is overridden by a repository administrator. By default, branch protection rules do not apply to users with administrative permissions or those with roles allowing "bypass branch protections." Overriding this protection could weaken an organization''s security posture.


    ## Triage and response

    1. Determine if the change made by the actor is authorized.

    2. If the change was unauthorized or unexpected, initiate your organization''s incident response process and investigate.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
