name: GitHub private repository changed to public visibility Playbook
description: Detect when a GitHub repository changes its visibility to public.
severity: High
steps:
- name: Investigation
  description: 'This rule monitors GitHub audit logs for changes from private to public visibility. Private repositories often contain sensitive information and should only be made public with organizational approval.


    ## Triage and response


    1. Verify if the change made by the actor is authorized.

    2. If the change is unauthorized or unexpected, initiate your organization''s incident response process and conduct an investigation.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
