# schema: https://scanner.dev/schema/scanner-threat-hunting-query.v1.json
name: Google Workspace Application Added
description: |-
  Identifies when a Marketplace app is added in a Google Workspace organization. Installing certain apps may increase the organization's risk of data exfiltration/leakage and increase its attack surface.
query_text: |-
  %ingest.source_type:google_workspace
  action:ADD_APPLICATION
tags:
- google_workspace
- converted_yaral
