# schema: https://scanner.dev/schema/scanner-threat-hunting-query.v1.json
name: GitHub Environment Secret Accessed
description: |-
  Detects access to GitHub environment secrets.
query_text: "%ingest.source_type:github\naction:environment.get_secrets "
tags:
- github
- secrets
- credential_access
