# schema: https://scanner.dev/schema/scanner-threat-hunting-query.v1.json
name: GitHub Dependabot Vulnerability Alerts Disabled
description: |-
  Detects when vulnerability alerts are disabled for GitHub Dependabot.
query_text: |-
  %ingest.source_type:github
  action:business_dependabot_alerts.disable OR action:business_dependabot_alerts_new_repos.disable OR action:dependabot_alerts.disable OR action:dependabot_alerts_new_repos.disable OR action:dependabot_security_updates.disable OR action:dependabot_security_updates_new_repos.disable OR action:repository_vulnerability_alerts.disable
tags:
- github
- converted_yaral
