name: AWS IAM AdministratorAccess policy was applied to a group Playbook
description: Detect when the AdministratorAccess policy is attached to an AWS IAM
  group.
severity: Medium
steps:
- name: Investigation
  description: Monitor CloudTrail for instances where an attacker has attached the
    AdministratorAccess policy to an AWS IAM group using the AttachGroupPolicy API
    call.
- name: Triage
  description: "1. Determine if the user identity session name should have made an\
    \ API call.\n2. If the API call was not made by the user:\n  * Rotate user credentials.\n\
    \  * Review other API calls made by the user.\n  * Remove the AdministratorAccess\
    \ policy from the specified group using the aws-cli command to detach the group\
    \ policy.\n3. If the API call was made legitimately by the user:\n  * Assess if\
    \ the group requires the AdministratorAccess policy for its intended function.\n\
    \  * Advise the user to find the least privileged policy that allows the group\
    \ to operate as intended."
