name: AWS S3 Bucket Versioning Disable Playbook
description: 'Detects when S3 bucket versioning is disabled. Threat actors use this
  technique during AWS ransomware incidents prior to deleting S3 objects.


  References:

  * https://invictus-ir.medium.com/ransomware-in-the-cloud-7f14805bbe82


  False Positives:

  * AWS administrator legitimately disabling bucket versioning'
severity: Medium
steps:
- name: Investigation
  description: 'Detects when S3 bucket versioning is disabled. Threat actors use this
    technique during AWS ransomware incidents prior to deleting S3 objects.


    References:

    * https://invictus-ir.medium.com/ransomware-in-the-cloud-7f14805bbe82


    False Positives:

    * AWS administrator legitimately disabling bucket versioning'
