name: AWS EC2 Disable EBS Encryption Playbook
description: 'Identifies disabling of default Amazon Elastic Block Store (EBS) encryption
  in the current region.

  Disabling default encryption does not change the encryption status of your existing
  volumes.



  References:

  * https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DisableEbsEncryptionByDefault.html


  False Positives:

  * System Administrator Activities

  * DEV, UAT, SAT environment. You should apply this rule with PROD account only.'
severity: Medium
steps:
- name: Investigation
  description: 'Identifies disabling of default Amazon Elastic Block Store (EBS) encryption
    in the current region.

    Disabling default encryption does not change the encryption status of your existing
    volumes.



    References:

    * https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DisableEbsEncryptionByDefault.html


    False Positives:

    * System Administrator Activities

    * DEV, UAT, SAT environment. You should apply this rule with PROD account only.'
