name: AWS ECS cluster deleted Playbook
description: Detect when an attacker is destroying an ECS Cluster.
severity: Informational
steps:
- name: Investigation
  description: Monitor the DeleteCluster API call to detect if an ECS cluster is deleted.
- name: Triage
  description: "1. Determine if the user identity should be making the delete API\
    \ call.\n2. Contact the user to see if they intended to make this API call.\n\
    3. If the user did not make the API call:\n    * Rotate the credentials.\n   \
    \ * Investigate if the same credentials made other unauthorized API calls."
