name: AWS WAF web access control list modified Playbook
description: Detect updates to an AWS Web Application Firewall (WAF) Access Control
  List (ACL).
severity: Low
steps:
- name: Investigation
  description: Monitor AWS WAF logs and detect when the event name is "UpdateWebACL".
- name: Triage
  description: '1. Verify if the user identity is authorized to perform the "UpdateWebACL"
    API call on the account.

    2. If the API call was unauthorized, rotate the user''s credentials and investigate
    other successfully accessed APIs.'
