name: AWS Suspicious SAML Activity Playbook
description: 'Identifies when suspicious SAML activity has occurred in AWS. An adversary
  could gain backdoor access via SAML.


  References:

  * https://docs.aws.amazon.com/IAM/latest/APIReference/API_UpdateSAMLProvider.html

  * https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html


  False Positives:

  * Automated processes that uses Terraform may lead to false positives.

  * SAML Provider could be updated by a system administrator. Verify whether the user
  identity, user agent, and/or hostname should be making changes in your environment.

  * SAML Provider being updated from unfamiliar users should be investigated. If known
  behavior is causing false positives, it can be exempted from the rule.'
severity: Medium
steps:
- name: Investigation
  description: 'Identifies when suspicious SAML activity has occurred in AWS. An adversary
    could gain backdoor access via SAML.


    References:

    * https://docs.aws.amazon.com/IAM/latest/APIReference/API_UpdateSAMLProvider.html

    * https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html


    False Positives:

    * Automated processes that uses Terraform may lead to false positives.

    * SAML Provider could be updated by a system administrator. Verify whether the
    user identity, user agent, and/or hostname should be making changes in your environment.

    * SAML Provider being updated from unfamiliar users should be investigated. If
    known behavior is causing false positives, it can be exempted from the rule.'
