name: AWS S3 Data Management Tampering Playbook
description: 'Detects when a user tampers with S3 data management in Amazon Web Services.


  References:

  * https://github.com/elastic/detection-rules/pull/1145/files

  * https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html

  * https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLogging.html

  * https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketWebsite.html

  * https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketEncryption.html

  * https://docs.aws.amazon.com/AmazonS3/latest/userguide/setting-repl-config-perm-overview.html

  * https://docs.aws.amazon.com/AmazonS3/latest/API/API_RestoreObject.html


  False Positives:

  * A S3 configuration change may be done by a system or network administrator. Verify
  whether the user identity, user agent, and/or hostname should be making changes
  in your environment. S3 configuration change from unfamiliar users or hosts should
  be investigated. If known behavior is causing false positives, it can be exempted
  from the rule.'
severity: Low
steps:
- name: Investigation
  description: 'Detects when a user tampers with S3 data management in Amazon Web
    Services.


    References:

    * https://github.com/elastic/detection-rules/pull/1145/files

    * https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations.html

    * https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLogging.html

    * https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketWebsite.html

    * https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketEncryption.html

    * https://docs.aws.amazon.com/AmazonS3/latest/userguide/setting-repl-config-perm-overview.html

    * https://docs.aws.amazon.com/AmazonS3/latest/API/API_RestoreObject.html


    False Positives:

    * A S3 configuration change may be done by a system or network administrator.
    Verify whether the user identity, user agent, and/or hostname should be making
    changes in your environment. S3 configuration change from unfamiliar users or
    hosts should be investigated. If known behavior is causing false positives, it
    can be exempted from the rule.'
