name: AWS EFS Fileshare Modified or Deleted Playbook
description: 'Detects when a EFS Fileshare is modified or deleted.

  You can''t delete a file system that is in use.

  If the file system has any mount targets, the adversary must first delete them,
  so deletion of a mount will occur before deletion of a fileshare.



  References:

  * https://docs.aws.amazon.com/efs/latest/ug/API_DeleteFileSystem.html


  False Positives:

  * Unknown'
severity: Medium
steps:
- name: Investigation
  description: 'Detects when a EFS Fileshare is modified or deleted.

    You can''t delete a file system that is in use.

    If the file system has any mount targets, the adversary must first delete them,
    so deletion of a mount will occur before deletion of a fileshare.



    References:

    * https://docs.aws.amazon.com/efs/latest/ug/API_DeleteFileSystem.html


    False Positives:

    * Unknown'
