name: AWS EC2 Startup Shell Script Change Playbook
description: 'Detects changes to the EC2 instance startup script. The shell script
  will be executed as root/SYSTEM every time the specific instances are booted up.

  References:
  * https://github.com/RhinoSecurityLabs/pacu/blob/866376cd711666c775bbfcde0524c817f2c5b181/pacu/modules/ec2__startup_shell_script/main.py#L9

  False Positives:
  * Valid changes to the startup script'
severity: High
steps:
- name: Investigation
  description: 'Detects changes to the EC2 instance startup script. The shell script
    will be executed as root/SYSTEM every time the specific instances are booted up.

    References:
    * https://github.com/RhinoSecurityLabs/pacu/blob/866376cd711666c775bbfcde0524c817f2c5b181/pacu/modules/ec2__startup_shell_script/main.py#L9

    False Positives:
    * Valid changes to the startup script'
