name: AWS ElastiCache Security Group Created Playbook
description: 'Detects when an ElastiCache security group has been created.


  References:

  * https://github.com/elastic/detection-rules/blob/598f3d7e0a63221c0703ad9a0ea7e22e7bc5961e/rules/integrations/aws/persistence_elasticache_security_group_creation.toml


  False Positives:

  * A ElastiCache security group may be created by a system or network administrator.
  Verify whether the user identity, user agent, and/or hostname should be making changes
  in your environment. Security group creations from unfamiliar users or hosts should
  be investigated. If known behavior is causing false positives, it can be exempted
  from the rule.'
severity: Low
steps:
- name: Investigation
  description: 'Detects when an ElastiCache security group has been created.


    References:

    * https://github.com/elastic/detection-rules/blob/598f3d7e0a63221c0703ad9a0ea7e22e7bc5961e/rules/integrations/aws/persistence_elasticache_security_group_creation.toml


    False Positives:

    * A ElastiCache security group may be created by a system or network administrator.
    Verify whether the user identity, user agent, and/or hostname should be making
    changes in your environment. Security group creations from unfamiliar users or
    hosts should be investigated. If known behavior is causing false positives, it
    can be exempted from the rule.'
