name: AWS IAM S3Browser Templated S3 Bucket Policy Creation Playbook
description: 'Detects S3 browser utility creating Inline IAM policy containing default
  S3 bucket name placeholder value of "<YOUR-BUCKET-NAME>".


  References:

  * https://permiso.io/blog/s/unmasking-guivil-new-cloud-threat-actor


  False Positives:

  * Valid usage of S3 browser with accidental creation of default Inline IAM policy
  without changing default S3 bucket name placeholder value'
severity: High
steps:
- name: Investigation
  description: 'Detects S3 browser utility creating Inline IAM policy containing default
    S3 bucket name placeholder value of "<YOUR-BUCKET-NAME>".


    References:

    * https://permiso.io/blog/s/unmasking-guivil-new-cloud-threat-actor


    False Positives:

    * Valid usage of S3 browser with accidental creation of default Inline IAM policy
    without changing default S3 bucket name placeholder value'
