name: AWS STS GetSessionToken Misuse Playbook
description: 'Identifies the suspicious use of GetSessionToken. Tokens could be created
  and used by attackers to move laterally and escalate privileges.


  References:

  * https://github.com/elastic/detection-rules/pull/1213

  * https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html


  False Positives:

  * GetSessionToken may be done by a system or network administrator. Verify whether
  the user identity, user agent, and/or hostname should be making changes in your
  environment. GetSessionToken from unfamiliar users or hosts should be investigated.
  If known behavior is causing false positives, it can be exempted from the rule.'
severity: Low
steps:
- name: Investigation
  description: 'Identifies the suspicious use of GetSessionToken. Tokens could be
    created and used by attackers to move laterally and escalate privileges.


    References:

    * https://github.com/elastic/detection-rules/pull/1213

    * https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html


    False Positives:

    * GetSessionToken may be done by a system or network administrator. Verify whether
    the user identity, user agent, and/or hostname should be making changes in your
    environment. GetSessionToken from unfamiliar users or hosts should be investigated.
    If known behavior is causing false positives, it can be exempted from the rule.'
