name: Restore Public AWS RDS Instance Playbook
description: 'Detects the recovery of a new public database instance from a snapshot.
  It may be a part of data exfiltration.


  References:

  * https://github.com/RhinoSecurityLabs/pacu/blob/866376cd711666c775bbfcde0524c817f2c5b181/pacu/modules/rds__explore_snapshots/main.py


  False Positives:

  * Unknown'
severity: High
steps:
- name: Investigation
  description: 'Detects the recovery of a new public database instance from a snapshot.
    It may be a part of data exfiltration.


    References:

    * https://github.com/RhinoSecurityLabs/pacu/blob/866376cd711666c775bbfcde0524c817f2c5b181/pacu/modules/rds__explore_snapshots/main.py


    False Positives:

    * Unknown'
