name: AWS GuardDuty Important Change Playbook
description: 'Detects updates of the GuardDuty list of trusted IPs, perhaps to disable
  security alerts against malicious IPs.


  References:

  * https://github.com/RhinoSecurityLabs/pacu/blob/866376cd711666c775bbfcde0524c817f2c5b181/pacu/modules/guardduty__whitelist_ip/main.py#L9


  False Positives:

  * Valid change in the GuardDuty (e.g. to ignore internal scanners)'
severity: High
steps:
- name: Investigation
  description: 'Detects updates of the GuardDuty list of trusted IPs, perhaps to disable
    security alerts against malicious IPs.


    References:

    * https://github.com/RhinoSecurityLabs/pacu/blob/866376cd711666c775bbfcde0524c817f2c5b181/pacu/modules/guardduty__whitelist_ip/main.py#L9


    False Positives:

    * Valid change in the GuardDuty (e.g. to ignore internal scanners)'
