name: Cloudtrail SecretsManager secret retrieved from AWS CloudShell environment Playbook
description: Detect when an AWS secret is retrieved from a CloudShell environment.
severity: Medium
steps:
- name: Investigation
  description: Monitor CloudTrail for retrieval of AWS secrets from CloudShell. The
    threat group LUCR-3 uses CloudShell in the AWS management console to interact
    with the AWS API and retrieve secrets.
- name: Triage
  description: "1. Determine if the user performed this operation.\n2. If the API\
    \ calls were not made by the user:\n   * Rotate user credentials.\n   * Rotate\
    \ the retrieved secrets, if feasible.\n   * Investigate other API calls made by\
    \ the user.\n   * Initiate your organization's incident response process."
