name: EC2 Suspicious Get User Password Request Playbook
description: 'Identifies when a user makes `GetPasswordData` requests for multiple
  different EC2 instances.

  This API call retrieves the encrypted administrator password for an instance running
  Windows. Multiple requests may indicate an adversary attempting to escalate privileges
  or move laterally.'
severity: High
steps:
- name: Investigation
  description: 'Identifies when a user makes `GetPasswordData` requests for multiple
    different EC2 instances.

    This API call retrieves the encrypted administrator password for an instance running
    Windows. Multiple requests may indicate an adversary attempting to escalate privileges
    or move laterally.'
