name: Encrypted administrator password retrieved for Windows EC2 instance Playbook
description: Detect when a user attempts to retrieve the encrypted Administrator password
  for a Windows EC2 instance.
severity: Low
steps:
- name: Investigation
  description: Monitor CloudTrail for attempts to retrieve the encrypted Administrator
    password using the GetPasswordData API call.
- name: Triage
  description: "1. Verify if the user should have made the API call.\n2. If the API\
    \ call was not made by the user:\n   * Rotate user credentials.\n   * Check other\
    \ API calls made by the user.\n3. If the API call was made by the user:\n   *\
    \ Determine if the user should access the EC2 instance.\n   * If yes, advise them\
    \ to speak with the instance owner to resolve the issue.\n   * If no, review other\
    \ API calls made by the user for further investigation."
