name: Possible privilege escalation via AWS login profile manipulation Playbook
description: Detect if a user or role attempts to create or update the password for
  a specific IAM user.
severity: Low
steps:
- name: Investigation
  description: Monitor CloudTrail for attempts to create or update a password for
    an IAM user using the CreateLoginProfile or UpdateLoginProfile API calls.
- name: Triage
  description: "1. Determine if the user session should have made the API call.\n\
    2. If the API call was not made by the user:\n  - Rotate user credentials.\n \
    \ - Investigate other API calls made by the user.\n  - Remove any passwords created\
    \ by the user using the delete-login-profile command or the AWS Console.\n3. If\
    \ the API call was made by the user:\n  - Verify if the user should be making\
    \ this API call.\n  - If not, check for other API calls made by the user to assess\
    \ if further investigation is necessary."
