name: Secrets Manager High Frequency GetSecretValue API Calls Playbook
description: 'Identifies high frequency of `GetSecretValue` API calls to AWS Secrets
  Manager programmatically.

  This may indicate an adversary attempting to access sensitive information.'
severity: High
steps:
- name: Investigation
  description: 'Identifies high frequency of `GetSecretValue` API calls to AWS Secrets
    Manager programmatically.

    This may indicate an adversary attempting to access sensitive information.'
