name: STS Suspicious Federated Temporary Credential Request Playbook
description: This hunting query identifies when a user requests temporary federated
  credentials with a duration greater than 24 hours or with the `AdministratorAccess`
  policy attached. Federated users are typically given temporary credentials to access
  AWS services. A duration greater than 24 hours or the `AdministratorAccess` policy
  attached may indicate an adversary attempting to maintain access to AWS services
  for an extended period of time or escalate privileges.
severity: Medium
steps:
- name: Investigation
  description: This hunting query identifies when a user requests temporary federated
    credentials with a duration greater than 24 hours or with the `AdministratorAccess`
    policy attached. Federated users are typically given temporary credentials to
    access AWS services. A duration greater than 24 hours or the `AdministratorAccess`
    policy attached may indicate an adversary attempting to maintain access to AWS
    services for an extended period of time or escalate privileges.
