# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: Cloudflare Access Application Deleted
description: |-
  ## Goal
  Detects the deletion of a Cloudflare Access application.

  ## Strategy
  Monitor Cloudflare Audit Logs for `access_app_delete`.

  ## Triage and Response
  1. Identify the application and the user.
  2. Verify if this was planned.
  3. Restore the application configuration if accidental.
enabled: true
severity: High
query_text: "%ingest.source_type:cloudflare\nAction:access_app_delete "
time_range_s: 3600
run_frequency_s: 300
event_sink_keys:
- high_severity_alerts
tags:
- cloudflare
- access
- availability
