# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: GitHub Dependabot Vulnerability Alerts Disabled
description: |-
  ## Goal
  Detects when vulnerability alerts are disabled for GitHub Dependabot.

  ## Strategy
  Monitor for disablement of Dependabot alerts or updates.

  ## Triage and Response
  1. Identify the repository and the user.
  2. Re-enable Dependabot immediately.
  3. Investigate why it was disabled.
enabled: true
severity: High
query_text: |-
  %ingest.source_type:github
  action:business_dependabot_alerts.disable OR action:business_dependabot_alerts_new_repos.disable OR action:dependabot_alerts.disable OR action:dependabot_alerts_new_repos.disable OR action:dependabot_security_updates.disable OR action:dependabot_security_updates_new_repos.disable OR action:repository_vulnerability_alerts.disable
time_range_s: 1800
run_frequency_s: 300
event_sink_keys:
- high_severity_alerts
tags:
- github
- converted_yaral
