name: AWS GuardDuty Bruteforce Activity Detected Playbook
description: Detects when Amazon GuardDuty identifies brute force activity on an Amazon EC2 or Amazon RDS instance. This could indicate an attempt to gain unauthorized access through credential guessing.
severity: High
steps:
- name: Investigation
  description: 'Monitor GuardDuty findings for the detection of brute force attempts (finding types containing `BruteForce`). Capture relevant details such as the principal IP, user, and location to assess potential threats.


    ## Triage and response

    Investigate the detected brute force event to determine if it was authorized. Review the user agent, principal IPs, and other details to assess potential threats. Ensure that no unauthorized access attempts are occurring.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
