name: AWS GuardDuty Root Credential Usage Playbook
description: Detects usage of the AWS root account credentials.
severity: Critical
steps:
- name: Investigation
  description: Monitor GuardDuty findings for `Policy:IAMUser/RootCredentialUsage`. The root account has unrestricted access to all resources in the AWS account and its usage should be strictly monitored and limited to specific tasks that require it.
- name: Triage
  description: '1. Verify if the root account usage was authorized and expected.

    2. If unauthorized, assume the root account is compromised.

    3. Change the root password and rotate MFA immediately.

    4. Check for any unauthorized resources created or modified.'
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
