name: Atlassian Confluence Space Export Playbook
description: |-
  Response steps for when a Confluence space is exported.
  Large exports can indicate data exfiltration.
severity: High
steps:
  - name: Triage
    description: |-
      1. Identify the user (`attributes.actor.email`) who performed the export.
      2. Identify the space exported.
  - name: Investigation
    description: |-
      1. Determine if this was authorized.
      2. Check the size and sensitivity of the exported space.
  - name: Remediation
    description: |-
      1. If unauthorized, investigate the user's device for exfiltrated data.
      2. Review the user's permissions.
