name: Google Workspace Marketplace Allowlist Configuration Playbook
description: Identifies when the Google Workspace Marketplace allowlist is configured to allow users to install and run any apps from the Marketplace. Allowing users to install and run any apps may increase the organization's risk of data exfiltration/leakage and increase its attack surface.
severity: Low
steps:
- name: Investigation
  description: Monitor Google Workspace audit logs for specific administrative or user actions.
- name: Triage
  description: '1. Identify the user and the action.

    2. Verify if the action was authorized.

    3. If unauthorized, revert the change and reset user credentials.'
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
