name: User attempted login with leaked password Playbook
description: Detect when a user attempts to log in with a known compromised password.
severity: Informational
steps:
- name: Investigation
  description: 'Monitor the Google Activity API call to identify if an attacker is trying to log in with a leaked password.


    ## Triage and response

    1. Identify the user in your organization with the compromised password.

    2. Contact the user to ensure they update their password on Google and any other accounts where the password may have been reused. Educate the user on strong password guidelines.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
