name: Google Cloud Pub/Sub Subscriber modified Playbook
description: Detect changes to Google Cloud Pub/Sub subscriptions that may prevent audit logs from being sent.
severity: Informational
steps:
- name: Investigation
  description: 'Monitor Google Cloud admin activity audit logs to identify when the following methods are invoked:


    * UpdateSubscription

    * DeleteSubscription


    ## Triage and response

    Review the subscription to ensure it is properly configured.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
