name: Google Cloud Service Account key created Playbook
description: Detect when a new service account key is created. An attacker could use this key as a backdoor to your account.
severity: Informational
steps:
- name: Investigation
  description: 'Monitor Google Cloud Admin activity audit logs to detect the creation of a service account key.


    ## Triage and response

    Contact the user who created the service account key to ensure they are managing it securely.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
