name: Google Cloud Logging Bucket deleted Playbook
description: Detect when a logging bucket is deleted in Google Cloud, as this may indicate defense evasion by an adversary.
severity: Medium
steps:
- name: Investigation
  description: 'Monitor Google Cloud audit logs for the invocation of the method:

    - `google.logging.v2.ConfigServiceV2.DeleteBucket`


    ## Triage and response

    Assess if the Google Cloud user should be deleting the logging bucket indicated by the resource name.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
