name: Google Cloud Service Account created Playbook
description: Detect when a new service account is created.
severity: Informational
steps:
- name: Investigation
  description: 'Monitor Google Cloud admin activity audit logs to identify the creation of service accounts.


    ## Triage and response

    Contact the user who created the service account to confirm its necessity and proper role scoping.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
