name: Google Cloud exposed service account key Playbook
description: Detect when Google Cloud disables a key due to exposure.
severity: Critical
steps:
- name: Investigation
  description: 'This rule monitors Cloud Audit Logs for instances when the principal disabled a key after detecting that it was exposed.


    ## Triage and response

    1. An abuse event is logged.

    2. Investigate any other actions performed by the compromised identity using the investigation tool.'
- name: Triage
  description: ''
- name: Remediation
  description: Follow the Triage steps to contain and remediate.
