# schema: https://scanner.dev/schema/scanner-threat-hunting-query.v1.json
name: AWS Config Disabling Channel/Recorder
description: |-
  Detects AWS Config Service disabling

  References:
  * https://docs.aws.amazon.com/config/latest/developerguide/cloudtrail-log-files-for-aws-config.html

  False Positives:
  * Valid change in AWS Config Service
query_text: |-
  %ingest.source_type="aws:cloudtrail"
  eventSource="config.amazonaws.com"
  eventName=(DeleteDeliveryChannel StopConfigurationRecorder)
  | stats
  min(@scnr.datetime) as firstTime,
  max(@scnr.datetime) as lastTime,
  count() as eventCount
  by
  userIdentity.arn,
  eventSource,
  eventName,
  awsRegion
tags:
- tactics.ta0005.defense_evasion
- techniques.t1562.impair_defenses
- source.cloudtrail
