# schema: https://scanner.dev/schema/scanner-threat-hunting-query.v1.json
name: Cloudtrail SecretsManager secret retrieved from AWS CloudShell environment
description: |-
  Detect when an AWS secret is retrieved from a CloudShell environment.
query_text: |-
  %ingest.source_type:"aws:cloudtrail"
  userAgent:*exec-env/CloudShell*
  eventName:GetSecretValue
  | groupbycount(userIdentity.arn)
  | where @q.count > 0
tags:
- techniques.t1555.credentials_from_password_stores
- tactics.ta0006.credential_access
- source.cloudtrail
