# schema: https://scanner.dev/schema/scanner-threat-hunting-query.v1.json
name: High EC2 Instance Deployment Count Attempts
description: |-
  Identifies when a user makes EC2 `RunInstances` API calls with a high instance deployment count.
  High instance deployment counts may indicate an adversary attempting to deploy a large number of instances for cryptomining or other malicious activities.
query_text: |-
  %ingest.source_type:aws:cloudtrail
  eventName:RunInstances
  eventSource:"ec2.amazonaws.com"
  | parse_json requestParameters "minCount", "maxCount"
  | eval target_instance_count = maxCount - minCount + 1
  | where target_instance_count >= 10
tags:
- tactics.ta0005.defense_evasion
- techniques.t1578.002.modify_cloud_compute_infrastructure
- source.aws.cloudtrail
